"""Tests for LaTeX (.tex/.ltx) container metadata inspection and cleaning.

route a LaTeX source as a container (like Markdown/HTML), strip the
compile-time PDF metadata it carries (\\hypersetup / \\pdfinfo) and the
provenance/tooling comment lines, and keep processing the body as text.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "service" / "scripts"
sys.path.insert(0, str(SCRIPTS))

from audit_lib import is_actionable, scan_file
from container_meta import (
    clean_latex,
    detect_container_format,
    inspect_latex,
    inspect_container,
)
from format_dispatch import classify, classify_bytes

ZWSP = chr(0x200B)

SAMPLE = r"""% !TEX program = pdflatex
% -*- coding: utf-8 -*-
% Generated by Claude
% vim:ft=tex:sw=2:ts=2
\documentclass{article}
\hypersetup{
  colorlinks=true,
  pdftitle={My Paper},
  pdfauthor={Jane Doe},
  pdfcreator={LaTeX with Claude},
  pdfproducer={pdfTeX},
}
\pdfinfo{/Title (My Paper) /Author (Jane Doe) /Creator (xelatex) /Producer (pdfTeX)}
\author{Jane Doe}
\title{My Paper}
\begin{document}
Hello \textbf{world}.
\end{document}
"""


def test_detect_container_format_latex():
    assert detect_container_format(Path("paper.tex")) == "latex"
    assert detect_container_format(Path("paper.ltx")) == "latex"


def test_classify_latex_is_container():
    assert classify(Path("paper.tex")) == "container"
    assert classify(Path("paper.ltx")) == "container"
    assert classify_bytes(SAMPLE.encode("utf-8"), ".tex") == "container"


def test_inspect_latex_flags_ai_provenance():
    c2pa, ai, findings, details = inspect_latex(SAMPLE)
    assert ai is True
    assert ["commands", "keys_dropped", "comments_dropped"] == [
        "commands",
        "keys_dropped",
        "comments_dropped",
    ]
    assert details["commands"] == 2
    assert details["keys_dropped"] >= 6
    assert details["comments_dropped"] >= 4
    # pdfcreator carries a Claude marker -> AI-flagged; a benign pdfauthor is info.
    assert any("pdfcreator" in f for f in findings)
    assert any("editor modeline" in f for f in findings)
    assert any("AI markers" in f for f in findings)
    assert any("pdfauthor" in f for f in findings)


def test_inspect_latex_marks_c2pa():
    doc = r"""\documentclass{article}
\hypersetup{pdftitle={x}, pdfcreator={Made with c2pa}}
\begin{document}hi\end{document}
"""
    c2pa, ai, findings, _ = inspect_latex(doc)
    assert c2pa is True
    assert ai is True


def test_inspect_container_routes_latex(tmp_path):
    p = tmp_path / "paper.tex"
    p.write_text(SAMPLE, encoding="utf-8")
    report = inspect_container(p)
    assert report.format == "latex"
    assert report.has_ai_metadata is True


def test_clean_latex_aggressive():
    out, actions = clean_latex(SAMPLE)
    # provenance fields stripped
    assert "pdfauthor=" not in out
    assert "pdfcreator=" not in out
    assert "pdfproducer=" not in out
    assert "/Author" not in out
    assert "/Creator" not in out
    assert "/Producer" not in out
    # kept: doc's own title, behavior key, visible content
    assert "pdftitle={My Paper}" in out
    assert "colorlinks=true" in out
    assert r"\author{Jane Doe}" in out
    assert r"\title{My Paper}" in out
    assert r"\textbf{world}" in out
    # comments / tooling lines dropped
    assert "% !TEX program" not in out
    assert "% -*- coding: utf-8 -*-" not in out
    assert "% Generated by Claude" not in out
    assert "% vim:" not in out
    assert "no LaTeX metadata removed" not in actions
    assert any("drop" in a for a in actions)


def test_clean_latex_keeps_plain_comments():
    doc = r"""% A perfectly ordinary comment.
\documentclass{article}
\begin{document}Hello.\end{document}
"""
    out, actions = clean_latex(doc)
    assert "% A perfectly ordinary comment." in out
    assert actions == ["no LaTeX metadata removed"]


def test_clean_latex_ignores_command_inside_comment():
    doc = r"""% \pdfinfo{/Creator (xelatex)}
\documentclass{article}
\begin{document}Hello.\end{document}
"""
    out, _ = clean_latex(doc)
    # The comment line is itself a tooling comment-free ordinary comment, so it
    # survives; the \pdfinfo inside it must NOT be treated as a live command.
    assert r"% \pdfinfo{/Creator (xelatex)}" in out


def test_latex_zero_width_surfaces_via_layer_a(tmp_path):
    """A hidden carrier in a .tex is found by the body Layer-A scan, so the
    audit treats it as actionable exactly as it would a .txt."""
    control = tmp_path / "control.txt"
    control.write_text(f"x{ZWSP}y\n", encoding="utf-8")
    subject = tmp_path / "carrier.tex"
    subject.write_text(f"\\begin{{document}}\nx{ZWSP}y\n\\end{{document}}\n", encoding="utf-8")

    control_item = scan_file(control)
    subject_item = scan_file(subject)

    assert subject_item["kind"] == "latex"
    assert subject_item["suspicious_total"] >= 1
    assert subject_item["has_ai_metadata"] is False  # no metadata, just a carrier
    assert is_actionable(subject_item) is is_actionable(control_item)
    assert is_actionable(subject_item) is True
